# Generated by Django 2.2.1 on 2019-05-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('introduction', models.TextField()),
                ('body', models.TextField()),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('categories', models.CharField(choices=[['TEC', 'Tecnología'], ['STA', 'Startups'], ['HEA', 'Salud'], ['POL', 'Politica']], max_length=3)),
            ],
        ),
    ]
